# Generated by Django 4.2 on 2025-03-03 13:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='link',
            old_name='adress',
            new_name='address',
        ),
    ]
